top_srcdir              ?= ../../../..

include $(top_srcdir)/include/mk/testcases.mk

INSTALL_TARGETS         := *.sh ftrace_stress/* ftrace_regression01 \
				ftrace_regression02

include $(top_srcdir)/include/mk/generic_leaf_target.mk
