# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) International Business Machines  Corp., 2007
# Copyright (C) 2021 SUSE LLC Andrea Cervesato <andrea.cervesato@suse.com>

top_srcdir		?= ../..

include $(top_srcdir)/include/mk/env_pre.mk

INTERNAL_LIB		= libltpclone.a

include $(top_srcdir)/include/mk/lib.mk
include $(top_srcdir)/include/mk/generic_leaf_target.mk
