# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) Huawei Technologies Co., Ltd., 2015
# Copyright (C) 2021 SUSE LLC Andrea Cervesato <andrea.cervesato@suse.com>

top_srcdir		?= ../../../..

include $(top_srcdir)/include/mk/testcases.mk

LDLIBS  := $(CAP_LIBS) $(LDLIBS)

include $(top_srcdir)/include/mk/generic_leaf_target.mk
