# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) Huawei Technologies Co., Ltd. 2021. All rights reserved.
# Author: Xie Ziyao <xieziyao@huawei.com>

top_srcdir		?= ../../../..

include $(top_srcdir)/include/mk/testcases.mk

include $(top_srcdir)/include/mk/generic_leaf_target.mk
